using System.Collections.Generic;

namespace OpenGGF.BizHawk.Headless
{
    /// <summary>
    /// Byte-exact port of the S1 complete-run recorder's run_manifest.json
    /// emitter (tools/bizhawk/s1_complete_run_recorder.lua
    /// write_run_manifest L785-849; spec s1-run-mode-behavior.md §6),
    /// delegating the structural layout to the shared
    /// <see cref="RunManifestWriter"/> core. S1 deltas versus S2: the game
    /// literal is "s1", rom_checksum is the inline "AFE05EEE" literal (S1
    /// World REV01 CRC32 — not computed at runtime), source_bk2 is rendered
    /// with Lua %q rather than json_escape, and the run_id line is emitted
    /// only when OGGF_TRACE_RUN_ID was set (the S1 detour machine is always
    /// on, so a manifest can exist without a run id whenever a detour
    /// occurred — pass null to omit the line). expected_movie_end_mode is
    /// likewise nullable: true movie completion records an authoritative
    /// mapped endpoint, while hard-stop and unknown endpoints omit it.
    ///
    /// lua_script_version is a capture-session input rather than an inline
    /// constant so the runner threads ONE session stamp through all three
    /// writers (level metadata, ss metadata, manifest); production captures
    /// pass <see cref="S1CompleteRunMetadataWriter.LuaScriptVersion"/>
    /// ("3.18", the current Lua's). The run segment metadata fixtures were
    /// captured by an interim script stamped "3.15"; the root manifest was
    /// regenerated by the 3.18 Lua authority with its observed endpoint.
    /// The ROM-backed differential gate pins the legacy segment-version
    /// substitution and compares the root manifest directly (spec §10).
    /// </summary>
    public static class S1RunManifestWriter
    {
        public const string RomChecksum = "AFE05EEE";

        public static string Format(
            string runId,
            string sourceBk2,
            string luaScriptVersion,
            string expectedMovieEndMode,
            IList<RunManifestSegment> segments,
            IList<RunManifestTransition> transitions,
            IList<DynamicArtGapTransition> dynamicArtGapTransitions = null)
        {
            return RunManifestWriter.Format(
                "s1",
                runId,
                sourceBk2,
                true,
                RomChecksum,
                luaScriptVersion,
                expectedMovieEndMode,
                segments,
                transitions,
                dynamicArtGapTransitions);
        }
    }
}
