param(
    [Parameter(Mandatory = $true)]
    [string]$LuaScript,

    [Parameter(Mandatory = $true)]
    [string]$WrapperPath
)

$ErrorActionPreference = "Stop"

$luaPath = (Resolve-Path -LiteralPath $LuaScript).Path
$raw = Get-Content -Raw -LiteralPath $luaPath

function Get-LuaLongClose([string]$text, [int]$start) {
    if ($start -ge $text.Length -or $text[$start] -ne '[') { return $null }
    $cursor = $start + 1
    while ($cursor -lt $text.Length -and $text[$cursor] -eq '=') { $cursor++ }
    if ($cursor -ge $text.Length -or $text[$cursor] -ne '[') { return $null }
    return ']' + (('=' * ($cursor - $start - 1)) -join '') + ']'
}

function Remove-LuaCommentsAndStrings([string]$text) {
    $result = [Text.StringBuilder]::new($text.Length)
    $lineComment = $false
    $quote = [char]0
    $escaped = $false
    $longClose = $null
    for ($i = 0; $i -lt $text.Length; $i++) {
        $current = $text[$i]
        if ($lineComment) {
            if ($current -eq "`n") { $lineComment = $false; [void]$result.Append("`n") }
            else { [void]$result.Append(' ') }
            continue
        }
        if ($null -ne $longClose) {
            if ($text.Substring($i).StartsWith($longClose, [StringComparison]::Ordinal)) {
                [void]$result.Append([char]' ', $longClose.Length)
                $i += $longClose.Length - 1
                $longClose = $null
            } elseif ($current -eq "`n") { [void]$result.Append("`n") }
            else { [void]$result.Append(' ') }
            continue
        }
        if ($quote -ne [char]0) {
            [void]$result.Append($(if ($current -eq "`n") { "`n" } else { ' ' }))
            if ($escaped) { $escaped = $false }
            elseif ($current -eq '\') { $escaped = $true }
            elseif ($current -eq $quote) { $quote = [char]0 }
            continue
        }
        if ($i + 1 -lt $text.Length -and $text.Substring($i, 2) -eq '--') {
            $close = Get-LuaLongClose $text ($i + 2)
            if ($null -ne $close) {
                [void]$result.Append([char]' ', $close.Length + 2)
                $i += $close.Length + 1
                $longClose = $close
            } else {
                [void]$result.Append('  ')
                $i++
                $lineComment = $true
            }
            continue
        }
        $close = Get-LuaLongClose $text $i
        if ($null -ne $close) {
            [void]$result.Append([char]' ', $close.Length)
            $i += $close.Length - 1
            $longClose = $close
            continue
        }
        if ($current -eq "'" -or $current -eq '"') {
            $quote = $current
            [void]$result.Append(' ')
            continue
        }
        [void]$result.Append($current)
    }
    return $result.ToString()
}

$executable = Remove-LuaCommentsAndStrings $raw
$validatedSource = $executable
if ($executable -match "ProbeRuntime\.run\s*\(") {
    $runtimePath = $env:OGGF_BIZHAWK_PROBE_RUNTIME
    $canonicalRuntimePath = (Resolve-Path -LiteralPath
        (Join-Path $PSScriptRoot "probes\probe_runtime.lua")).Path
    if ([string]::IsNullOrWhiteSpace($runtimePath) -or
        -not [IO.Path]::IsPathRooted($runtimePath) -or
        -not (Test-Path -LiteralPath $runtimePath) -or
        -not ((Resolve-Path -LiteralPath $runtimePath).Path.Equals(
            $canonicalRuntimePath, [StringComparison]::OrdinalIgnoreCase))) {
        Write-Host "ERROR: OGGF_BIZHAWK_PROBE_RUNTIME must name the canonical absolute probe runtime."
        exit 1
    }
    $validatedSource = Remove-LuaCommentsAndStrings (Get-Content -Raw -LiteralPath $canonicalRuntimePath)
}
$preLoop = [regex]::Split($validatedSource, "while\s+true|emu\.frameadvance\s*\(", 2)[0]
$missing = @()
if ($preLoop -notmatch "emu\.limitframerate\s*\(\s*false\s*\)") {
    $missing += "emu.limitframerate(false)"
}
if ($preLoop -notmatch "client\.speedmode\s*\(\s*6400\s*\)") {
    $missing += "client.speedmode(6400)"
}
if ($preLoop -notmatch "client\.invisibleemulation\s*\(\s*true\s*\)") {
    $missing += "client.invisibleemulation(true)"
}
if ($preLoop -notmatch "client\.SetSoundOn[\s\S]{0,80}false") {
    $missing += "client.SetSoundOn(false)"
}

if ($missing.Count -gt 0) {
    Write-Host ("ERROR: Lua diagnostic is missing executable fast-headless template call(s) before its main loop: " + ($missing -join ", "))
    Write-Host "Copy tools\bizhawk\diag_template_fast.lua or set BIZHAWK_ALLOW_SLOW_LUA=1 for deliberate visible debugging."
    exit 1
}

if ($validatedSource -match "client\.invisibleemulation\s*\(\s*false\s*\)" -or
    $validatedSource -match "client\.SetSoundOn[\s\S]{0,80}true") {
    Write-Host "ERROR: Lua diagnostic re-enables rendering or sound. Set BIZHAWK_ALLOW_SLOW_LUA=1 for deliberate visible debugging."
    exit 1
}

$luaLiteral = $luaPath.Replace("\", "\\").Replace('"', '\"')

$wrapper = @"
-- Generated by tools/bizhawk/run_bizhawk_lua.bat. Do not edit.
local target = "$luaLiteral"
dofile(target)
"@

$wrapperDir = Split-Path -Parent $WrapperPath
if ($wrapperDir -and -not (Test-Path -LiteralPath $wrapperDir)) {
    New-Item -ItemType Directory -Force -Path $wrapperDir | Out-Null
}
Set-Content -NoNewline -LiteralPath $WrapperPath -Value $wrapper
