param(
    [Parameter(Mandatory = $true)]
    [string]$LuaScript,

    [Parameter(Mandatory = $true)]
    [string]$WrapperPath
)

$ErrorActionPreference = "Stop"

$luaPath = (Resolve-Path -LiteralPath $LuaScript).Path
$raw = Get-Content -Raw -LiteralPath $luaPath

function Remove-LuaComments([string]$text) {
    $withoutBlocks = [regex]::Replace($text, "--\[(=*)\[(?s:.*?)\]\1\]", "")
    $lines = $withoutBlocks -split "`r?`n"
    $stripped = foreach ($line in $lines) {
        $idx = $line.IndexOf("--", [StringComparison]::Ordinal)
        if ($idx -ge 0) {
            $line.Substring(0, $idx)
        } else {
            $line
        }
    }
    return ($stripped -join "`n")
}

$executable = Remove-LuaComments $raw
$validatedSource = $executable
if ($executable -match "OGGF_BIZHAWK_PROBE_RUNTIME" -and
    $executable -match "ProbeRuntime\.run\s*\(") {
    $runtimePath = Join-Path (Split-Path -Parent $luaPath) "probe_runtime.lua"
    if (-not (Test-Path -LiteralPath $runtimePath)) {
        Write-Host "ERROR: Delegated probe runtime not found beside probe: $runtimePath"
        exit 1
    }
    $validatedSource = Remove-LuaComments (Get-Content -Raw -LiteralPath $runtimePath)
}
$preLoop = [regex]::Split($validatedSource, "while\s+true|emu\.frameadvance\s*\(", 2)[0]
$missing = @()
if ($preLoop -notmatch "emu\.limitframerate\s*\(\s*false\s*\)") {
    $missing += "emu.limitframerate(false)"
}
if ($preLoop -notmatch "client\.speedmode\s*\(\s*6400\s*\)") {
    $missing += "client.speedmode(6400)"
}
if ($preLoop -notmatch "client\.invisibleemulation\s*\(\s*true\s*\)") {
    $missing += "client.invisibleemulation(true)"
}
if ($preLoop -notmatch "client\.SetSoundOn[\s\S]{0,80}false") {
    $missing += "client.SetSoundOn(false)"
}

if ($missing.Count -gt 0) {
    Write-Host ("ERROR: Lua diagnostic is missing executable fast-headless template call(s) before its main loop: " + ($missing -join ", "))
    Write-Host "Copy tools\bizhawk\diag_template_fast.lua or set BIZHAWK_ALLOW_SLOW_LUA=1 for deliberate visible debugging."
    exit 1
}

if ($validatedSource -match "client\.invisibleemulation\s*\(\s*false\s*\)" -or
    $validatedSource -match "client\.SetSoundOn[\s\S]{0,80}true") {
    Write-Host "ERROR: Lua diagnostic re-enables rendering or sound. Set BIZHAWK_ALLOW_SLOW_LUA=1 for deliberate visible debugging."
    exit 1
}

$luaLiteral = $luaPath.Replace("\", "\\").Replace('"', '\"')

$wrapper = @"
-- Generated by tools/bizhawk/run_bizhawk_lua.bat. Do not edit.
local target = "$luaLiteral"
dofile(target)
"@

$wrapperDir = Split-Path -Parent $WrapperPath
if ($wrapperDir -and -not (Test-Path -LiteralPath $wrapperDir)) {
    New-Item -ItemType Directory -Force -Path $wrapperDir | Out-Null
}
Set-Content -NoNewline -LiteralPath $WrapperPath -Value $wrapper
